### PR TITLE
Features

### PR DESCRIPTION
**Pull request by ybadmus**
Building with Responsive Design - Initial Pull Request

### CODE REVIEW

**Review by PhillipUg — COMMENTED** [review]
# Invalid Submission 🔴 

- [ ] Your readme file needs some work.

**Friendly reminder:** You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

If you have any questions, feel free to send me a message through Slack **Phillip Musiime**

I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @ybadmus, 👏 You did very well on this project. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] Fix web hint and stylelint linting errors
- [x] In the medium version(medium-size screens), the TNW logo should appear at the leftmost part.
- [ ] The top 3 articles section should be responsive as to the original page.
- [ ] In the latest Funding section, articles should be displayed 4, 3, or 1 per row respectively on large, medium, and small screen devices.
- [ ] In the Categories (Apps, Gear, Tech, etc) section, articles should be displayed  3, 2, or 1 per row respectively on large, medium, and small screen devices.
- [x] Add the latest deals section.
- [x] Add the footer
- [ ] You should use min-width around 768px for medium screens and min-width 1024px for large screens
- [x] Add setup instruction in the readme.
- [x] Add the debug.log log file in the .gitignore

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

Hey there @ybadmus you did very well in implementing most of the changes as required by the TSE's. You are almost there, don't give up  😄 we want you to be the best 💯 . Now let's fix these issues, they are all mandatory:

- [ ]  Fix web hint and stylelint linting errors

**Top 3 articles section**
 ###### Medium version changes
* [ ] It contains one bigger image on the leftmost part of the row (around two-thirds of the width) ([link to page](https://thenextweb.com/))
* [ ] It contains two smaller images on the rightmost part of the row (one above another) ([link to page](https://thenextweb.com/))
Check out the screenshot below ⬇️ 
- Original
s1
 - Clone
s2

**Latest news section**
###### Medium version changes

* [ ] It aligns 3 articles per row ([link to page](https://thenextweb.com/))
Check out the screenshot below ⬇️ 
- Original
s3
- Clone
s4

**Latest Funding section**
###### Medium version changes
It aligns 3 articles per row ([link to page](https://thenextweb.com/))
Check out the screenshot below ⬇️ 
- Original
s5
- Clone
s6

** Latest deals section**
###### Medium version changes
* [ ] It aligns 3 deals per row ([link to page](https://thenextweb.com/))
Check out the screenshot below ⬇️
- Original
s7

- Clone
s8

** Implementation details **
- Reduce the font sizes on the latest news and latest deals section especially on mobile and tablet view
-  To help with breakpoints use medium: min-width around 768px, large: min-width 1024px, no small breakpoint as it is mobile first and the base styles are for the mobile screen

That's all 😄   fix the issues raised above and submit another review when done.
Happy Coding 💻  🖱️ 💯 

Regards 
Peris Ndanu
If you need any further clarification contact me on slack (@perisndanu)

**Comment by ybadmus** [comment]
Hello Pres,

Looks like you didn't get the latest code because the medium screen issue had been resolved before submitting for review. Anyway I will fix the stylelint errors and submit again. Thanks

**Review by layzrd — CHANGES_REQUESTED** [review]
Status: Require changes 🌳 ♲
Hi @ybadmus, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE in this PR. 👏 👏  ✨ I applaud you for your hard work in replicating thenextweb.com. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] Fix web hint and stylelint linting errors
- [ ] The top 3 articles section should be responsive as to the original page.
- [ ] The TNW logo on the top article should not appear on small screens.
Screen Shot 2020-11-19 at 9 07 47 PM
Screen Shot 2020-11-19 at 9 07 34 PM

- [ ] Add the article's text on the top news.
Screen Shot 2020-11-19 at 9 28 54 PM
Screen Shot 2020-11-19 at 9 49 01 PM

- [ ] The footer background color should be similar to the original website.
original
yours

- [ ] Remove the debug.log file from the GitHub(remote) repository. Add the log file in the .gitignore

Kindly, I strongly urge you to check all the requirements before requesting a code review.

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @ybadmus, 👏👏  I appreciate your hard work in replicating thenextweb.com. Most requirements have been done 👌. But, you should achieve the requirements before approving this project and going to the next one. Kindly fix the issues we requested you to implement in the above comment. 

If you have any questions, [connect me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2).

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Connect me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by ybadmus** [comment]
Hi @abredi What changes, you didn't mention them. I have resolved all the changes requested. I don't know what changes you are talking about. Kindly clone the project to your local machine and test again.

**Comment by layzrd** [comment]
Hello @ybadmus, how you doing?
When I was writing a comment for you, there was an issue the same as the previous request including, the linting error in Github.
That's why I referred you to check the previous comment.
Now everything looks good, kindly create a new request.

**Comment by kelvin8773** [comment]
# Change Required 😭 💅 👨‍💻 

Hi, Yusif,

Thanks for sticking around and working hard on this project, I think you have done a good job to make your project visually appealing and tried to perfect everything you can think of, what a good spirit, and please keep it up! 👍 💯 

However, I want to stress you again on the purpose of this project - **make a responsive website**, which means that you should make your project respond to the various screen, accordingly (align with the original website):
 - Large screen - equal or over 1024 px
- Medium screen - equal or over 768 px
- Small screen - smaller than 768 px

After checking out your previous commits and multiple PR request, you seem to miss the point Here - your project is consistently missing or not following the same behavior as the original website does. 

Let's check out the following screen for example:
latest_news_errors

And beyond this "latest news" section, "latest Funding Section", "Categories Section",  "Latest deals section", also have a similar issue, please try reference the original website at the given breakpoint I show above and fix them accordingly. (The good news is they are easy fixes)

* ### latest Funding Section
Snipaste_2020-11-20_15-09-26

* ### Categories Section
Snipaste_2020-11-20_15-17-23

* ### Latest deals section
Snipaste_2020-11-20_15-19-46

I hope this comment is making sense for you and you will learn more while you try to fix those issues.

Feel free to contact me at Slack @kelvin any time if you are still confused, thanks again for your patience and good luck!

Best
Kelvin

**Comment by ybadmus** [comment]
I am sure you are having these issues due to the raw.githack hosting
service.  It seems you are not getting my latest changes.  Please clone the
project and run it on your localhost.

All the issues you mentioned have been resolved in previous commits.

Best Regards,
Yusuf

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to announce that your project is approved.
Congratulations on achieving this milestone in your career. :clap:

_I am looking forward to seeing your next project._

-----------------------------------------------------------------------------------------------

**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
